### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by benbjohnson** [turingschool-examples/pie#1]
Maintain database and table metadata with in-memory structures. 
### Tasks
- [x] Create metadata structures.
- [x] `Database.Table(name string) *Table`
- [x] `Database.CreateTable(name string, columns []*Column) error`
- [x] `Database.DeleteTable(name string) error`
