### ISSUE TITLE
UI: Table Listing

### ISSUE THREAD

**Issue by benbjohnson** [turingschool-examples/pie#3]
Add a UI for listing all tables in the database.
### Tasks
- [x] Add route to `Handler`.
- [x] Retrieve tables from database.
- [x] Write HTML to `http.ResponseWriter`.
