### ISSUE TITLE
UI: Create Table

### ISSUE THREAD

**Issue by benbjohnson** [turingschool-examples/pie#5]
Add an endpoint for uploading a CSV file and creating a new table.
### Tasks
- [x] Add route to handler.
- [x] Create CSVImporter
- [x] Extract filename from HTTP body
- [x] Add file picker for upload.
- [x] Drag-and-drop file into window to upload.
