### ISSUE TITLE
UI: Delete Table

### ISSUE THREAD

**Issue by benbjohnson** [turingschool-examples/pie#6]
Add an endpoint for deleting a table.
### Tasks
- [ ] Add route to handler.
- [ ] Read table name from URL.
- [ ] Delete table from database.
